### ISSUE TITLE
Combine functions for deposits and withdrawal into transaction

### ISSUE THREAD

**Issue by mharty3** [andrerwolff/PFT#14]
Do you think it would be better to combine the functions for deposits and withdrawals into one transaction function? It can ask the user if the transaction is a deposit or a withdrawal. That way if we need to make any changes to how we want to implement the transaction function we will only need to change it once rather than in the deposit and the withdrawal functions. The option text will be for users to record a transaction. 

On a similar note, I think the user should have the option to deposit into any envelope. It should default to the income pool (maybe press y to deposit into income pool), but I think it is more clear if the user knows where the money is going. Also there are some times where you would want to deposit directly into an envelope.

Let me know your thoughts

**Comment by andrerwolff** [comment]
I seem to remember a reason I split them out, but it would probably be just as easy to combine them and simplify things. I have a tendency to err on the side of separating things then combine if it makes sense. Rather than build monster functions and divide up later.

**Comment by mharty3** [comment]
Ok. Yes, I like that philosophy.
