### ISSUE TITLE
Payee Tracking

### ISSUE THREAD

**Issue by mharty3** [andrerwolff/PFT#3]
We should keep track of who is giving us money and where our money is going

- [x] Create DB Table for Payee
- [x] When entering transactions, allow user to select payee

**Comment by andrerwolff** [comment]
What are you thinking this will hold? If i understand it right you want to track Payer and Payee?
So when there is a deposit it records like Merrick & Company, Ally Bank Interest, Friend, etc... and when there is a withdrawal it records like Costco, Rental Management Company, Xcel Power, etc...?

Should this be required for input or just like "Select payee (or enter to skip): " then default to like 'Other'?
